version: '3.8'
services:
  app:
    build: .
    image: vehicles-example-api
    command: bundle exec rails s -b 0.0.0.0
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      -  postgres_data:/var/lib/postgresql/data
      -  ./postgres-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    logging:
      driver: none

volumes:
  postgres_data:
