default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  user: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vehicles_dev

test:
  <<: *default
  database: vehicles_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
